server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:h2:mem:///exchange_db
    username: sa
    password: password
  h2:
    console:
      enabled: true
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      mode: always
  security:
    jwt:
      secret: mysecretkey
      expiration: 3600

logging:
  level:
    org.springframework: INFO